### ISSUE TITLE
pyaml does not handle python tuples

### ISSUE THREAD

**Issue by ablot** [znamlab/flexiznam#16]
pyaml cannot load tuples. 
38639b8 replaces the tuple by a list. The generated config file looks like that:

```
data_subfolder:
  processed: processed
  raw: raw
datatypes:
- mouse
- session
- recording
- dataset
download_folder: ~/Downloads
flexilims_username: blota
mcms_username: ab8
project_ids:
  3d_vision: 606df5af08df4d77c72c9b05
  AAVRKO_retina_hva: 60a7757a8901a2357f29080a
  test: 606df1ac08df4d77c72c9aa4
  virus_tests: 607f145d25d64b66227b00be
projects_root: /camp/lab/znamenskiyp/home/shared/projects
```

The datatype field is then loaded as a list. Is that what you need @znamensk?
